# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 01:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Name')),
                ('client_type', models.CharField(choices=[('confidential', 'Confidential'), ('public', 'Public')], default='confidential', help_text='<b>Confidential</b> clients are capable of maintaining the confidentiality of their credentials. <b>Public</b> clients are incapable.', max_length=30, verbose_name='Client Type')),
                ('client_id', models.CharField(max_length=255, unique=True, verbose_name='Client ID')),
                ('client_secret', models.CharField(blank=True, default='', max_length=255, verbose_name='Client SECRET')),
                ('response_type', models.CharField(choices=[('code', 'code (Authorization Code Flow)'), ('id_token', 'id_token (Implicit Flow)'), ('id_token token', 'id_token token (Implicit Flow)')], max_length=30, verbose_name='Response Type')),
                ('jwt_alg', models.CharField(choices=[('HS256', 'HS256'), ('RS256', 'RS256')], default='RS256', max_length=10, verbose_name='JWT Algorithm')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date Created')),
                ('_redirect_uris', models.TextField(default='', help_text='Enter each URI on a new line.', verbose_name='Redirect URIs')),
                ('product', models.OneToOneField(default=-1, help_text='Product related to this client', on_delete=django.db.models.deletion.CASCADE, related_name='oidc_client', to='subscriptions.SubscriptionProduct')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires_at', models.DateTimeField(verbose_name='Expiration Date')),
                ('_scope', models.TextField(default='', verbose_name='Scopes')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='Code')),
                ('nonce', models.CharField(blank=True, default='', max_length=255, verbose_name='Nonce')),
                ('is_authentication', models.BooleanField(default=False, verbose_name='Is Authentication?')),
                ('code_challenge', models.CharField(max_length=255, null=True, verbose_name='Code Challenge')),
                ('code_challenge_method', models.CharField(max_length=255, null=True, verbose_name='Code Challenge Method')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oidc_provider.Client', verbose_name='Client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Authorization Code',
                'verbose_name_plural': 'Authorization Codes',
            },
        ),
        migrations.CreateModel(
            name='RSAKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(help_text='Paste your private RSA Key here.', verbose_name='Key')),
            ],
            options={
                'verbose_name': 'RSA Key',
                'verbose_name_plural': 'RSA Keys',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires_at', models.DateTimeField(verbose_name='Expiration Date')),
                ('_scope', models.TextField(default='', verbose_name='Scopes')),
                ('access_token', models.CharField(max_length=255, unique=True, verbose_name='Access Token')),
                ('refresh_token', models.CharField(max_length=255, null=True, unique=True, verbose_name='Refresh Token')),
                ('_id_token', models.TextField(verbose_name='ID Token')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oidc_provider.Client', verbose_name='Client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
            },
        ),
        migrations.CreateModel(
            name='UserConsent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires_at', models.DateTimeField(verbose_name='Expiration Date')),
                ('_scope', models.TextField(default='', verbose_name='Scopes')),
                ('date_given', models.DateTimeField(verbose_name='Date Given')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oidc_provider.Client', verbose_name='Client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='userconsent',
            unique_together=set([('user', 'client')]),
        ),
    ]
