# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-10 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_provider', '0002_oidc_provider_0_4_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconsent',
            name='device_id',
            field=models.CharField(max_length=255, null=True, verbose_name='Device ID'),
        ),
    ]
